### ISSUE TITLE
Problems with headers.pickle

### ISSUE THREAD

**Issue by Binerax** [JimAppreciator512/ifunny-bot#52]
Running docker compose up returns FileNotFoundError: [Errno 2] No such file or directory: 'ifunnybot/data/headers.pickle'

**Comment by JimAppreciator512** [comment]
The file isn't included in the repo just as the token for the bot is, you'll have to obtain those headers yourself.

**Comment by Binerax** [comment]
Apologies, I'm not really familiar with python or docker. How do I go about obtaining them?

**Comment by JimAppreciator512** [comment]
basically:
1. copy the headers from some random HTTP request, i.e., go to youtube, copy the **request** headers
2. format them into a python dictionary
3. use the pickle module to dump that dictionary into a file
4. put it in ifunnybot/data/headers.pickle

I might redo this process because it's a little unintuitive, I'm in the process of rewriting the bot so there are things that aren't documented.
